baseURL = '/'
languageCode = 'en-us'
title = 'Linus Rogge'

[Params]
    description = 'Software Designer'
    # status = 'Falling in love with <a href="https://antonstallboerger.com">Anton</a>'
    status = 'Happy Pride Month 🏳️‍🌈'

[author]
    name = 'Linus Rogge'
    email = 'hello@linusrogge.com'

[menu]
[[menu.footer]]
    name = "Work"
    url = "/work"
    weight = 1
[[menu.footer]]
    name = "Timeline"
    url = "/timeline"
    weight = 2
[[menu.footer]]
    name = "About"
    url = "/about"
    weight = 3
[[menu.footer]]
    name = "House"
    url = "/house"
    weight = 4
[[menu.footer]]
    name = "Uses"
    url = "/uses"
    weight = 5

[[menu.socials]]
    name = "Twitter"
    url = "https://twitter.com/linusrogge"
[[menu.socials]]
    name = "Cosmos"
    url = "https://cosmos.so/linusrogge"
[[menu.socials]]
    name = "Instagram"
    url = "https://instagram.com/linusrgge"
[[menu.socials]]
    name = "Read.cv"
    url = "https://read.cv/linusrogge"

[[menu.legals]]
    name = "Imprint"
    url = "/imprint"
    weight = 2
[[menu.legals]]
    name = "Colophon"
    url = "/colophon"
    weight = 1

# [markup.goldmark.renderer]
#    unsafe = true
